name: CI/CD

on:
  release:
    types: [created]  # Запускать только при создании релиза

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  # Обновлено на v2
      - name: Install Bluetooth
        run: sudo apt-get install -y build-essential libbluetooth-dev
      - name: Install dependencies
        run: npm install
      - name: Build Linux
        run: npm run build:linux
      - name: Create out directory and copy artifacts
        run: |
          mkdir out
          cp dist/linux.AppImage out/
          cp dist/linux.deb out/
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2  # Обновлено на v2
        with:
          name: linux
          path: out

  build-mac:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2  # Обновлено на v2
      - uses: actions/setup-node@v2  # Обновлено на v2
        with:
          node-version: '8.x'
      - name: Install dependencies
        run: npm install
      - name: Build Mac
        run: npm run build:mac
      - name: Create out directory and copy artifacts
        run: |
          mkdir out
          cp dist/mac.pkg out/
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2  # Обновлено на v2
        with:
          name: mac
          path: out

  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2  # Обновлено на v2
      - uses: actions/setup-node@v2  # Обновлено на v2
        with:
          node-version: '8.x'
      - name: Install dependencies
        run: npm install
      - name: Build Windows
        run: npm run build:win
      - name: Create out directory and copy artifacts
        run: |
          mkdir out
          copy dist\win.exe out\
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2  # Обновлено на v2
        with:
          name: win
          path: out

upload:
  runs-on: ubuntu-latest 
  needs: [build-linux, build-mac, build-win]
  steps:
    - uses: actions/checkout@v2  # Обновлено на v2

    - name: Download Linux artifact 
      uses: actions/download-artifact@v2  # Обновлено на v2 
      with:
        name: linux

    - name: Download Mac artifact 
      uses: actions/download-artifact@v2  # Обновлено на v2 
      with:
        name: mac

    - name: Download Windows artifact 
      uses: actions/download-artifact@v2  # Обновлено на v2 
      with:
        name: win

    - name: Upload to Release .deb 
      uses: JasonEtco/upload-to-release@v0.1.1 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with:
        args: linux/linux.deb application/vnd.debian.binary-package 

    - name: Upload to Release AppImage 
      uses: JasonEtco/upload-to-release@v0.1.1 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with:
        args: linux/linux.AppImage application/x-executable 

    - name: Upload to Release .pkg 
      uses: JasonEtco/upload-to-release@v0.1.1 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with:
        args: mac/mac.pkg application/x-xar 

    - name: Upload to Release .exe 
      uses: JasonEtco/upload-to-release@v0.1.1 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with:
        args: win/win.exe application/octet-stream 