name: Release Workflow

on:
  push:
    tags:
      - 'v*'  # Запускать при создании тегов, начинающихся с v

jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build for Linux
        run: |
          # Здесь ваши команды для сборки на Linux
          mkdir appdir
          echo "Linux build artifact" > appdir/linux-artifact.txt
          
      - name: Create Linux artifact  
        run: |
          # Создание архива с артефактами для Linux
          tar -czf linux-artifact.tar.gz -C appdir .
          
      - name: Upload Linux artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-artifact
          path: linux-artifact.tar.gz
          
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Build for macOS
        run: |  
          # Здесь ваши команды для сборки на macOS
          mkdir appdir
          echo "macOS build artifact" > appdir/macos-artifact.txt

      - name: Create macOS artifact
        run: |
          # Создание архива с артефактами для macOS
          tar -czf macos-artifact.tar.gz -C appdir .
          
      - name: Upload macOS artifact  
        uses: actions/upload-artifact@v3
        with:
          name: macos-artifact
          path: macos-artifact.tar.gz

  create-releases:
    needs: [build-linux, build-macos]
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Download Linux artifact
        uses: actions/download-artifact@v3
        with:
          name: linux-artifact
        
      - name: Download macOS artifact  
        uses: actions/download-artifact@v3
        with:
          name: macos-artifact
        
      - name: Create Linux Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Linux Release ${{ github.ref }}
          files: linux-artifact.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create macOS Release  
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}  
          release_name: macOS Release ${{ github.ref }}
          files: macos-artifact.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}