name: Release Workflow

on:
  push:
    tags:
      - 'v*'  # Запускать при создании тегов, начинающихся с v

jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build for Linux
        run: |
          # Команды для сборки на Linux
          ./configure --prefix=/usr
          make
          make install DESTDIR=appdir
          
      - name: Create Linux artifact  
        run: |
          # Создание архива с артефактами для Linux
          cd appdir
          tar -czf ../linux-artifact.tar.gz .
          
      - name: Upload Linux artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux-artifact
          path: linux-artifact.tar.gz
          
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Build for macOS
        run: |  
          # Команды для сборки на macOS
          ./configure --prefix=/usr
          make
          make install DESTDIR=appdir
          
      - name: Create macOS artifact
        run: |
          # Создание архива с артефактами для macOS
          cd appdir
          tar -czf ../macos-artifact.tar.gz .
          
      - name: Upload macOS artifact  
        uses: actions/upload-artifact@v2
        with:
          name: macos-artifact
          path: macos-artifact.tar.gz
          
  create-releases:
    needs: [build-linux, build-macos]
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Download Linux artifact
        uses: actions/download-artifact@v2
        with:
          name: linux-artifact
          
      - name: Download macOS artifact  
        uses: actions/download-artifact@v2
        with:
          name: macos-artifact
          
      - name: Create Linux Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: Linux Release ${{ github.ref }}
          files: linux-artifact.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create macOS Release  
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}  
          name: macOS Release ${{ github.ref }}
          files: macos-artifact.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}