name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]  # Указываем операционные системы

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up CMake
        run: |
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            sudo apt-get install cmake g++ -y  # Установка CMake и компилятора для Linux
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            brew install cmake gcc  # Установка CMake и компилятора для macOS
          fi

      - name: Build with CMake
        run: |
          mkdir build           # Создание директории для сборки
          cd build              # Переход в директорию сборки
          cmake ..              # Генерация файлов сборки
          make                  # Сборка проекта

      - name: Run
        run: |
          ./build/hello        # Запуск скомпилированной программы